name: Supabase Keep Alive

on:
  schedule:
    # Berjalan setiap 3 hari sekali (Jam 00:00 UTC)
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Memungkinkan kamu menjalankan manual untuk tes

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/persil?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"